id: I4EA39E60
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:29.037436
last_modified: 2023-01-04 11:29:29.037454
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  598D:
    title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
    base_file: 598D.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
